build:
  environment:
    node: v13.9.0
  nodes:
    analysis:
      project_setup:
        override: true
      tests:
        override: [js-scrutinizer-run]
    coverage:
      tests:
        before:
          - command: 'git clone https://github.com/sonnerberg/jsramverk-backend backend && npm run install --prefix backend && npm run start:test'
            background: true
          - command: 'npm install -g serve'
            background: true
          - command: 'npm run build'
            background: true
          - command: 'serve -s -l 3000 build'
            background: true

        override:
          - command: npm test
            coverage:
              file: coverage/clover.xml
              format: clover
