language: node_js
node_js:
  - 14
  - 13
  - 12
  - 11
  - 10
before_install:
  - git clone https://github.com/sonnerberg/jsramverk-backend backend
  - npm install
  - npm install --prefix backend
before_script:
  - npm run pretest --prefix backend
  - npm run start:test --prefix backend &
  - (npm run start&)
script:
  - npm test
