language: node_js
node_js:
  - 14
  - 13
  - 12
  - 11
  - 10
before_install:
  - git clone https://github.com/sonnerberg/jsramverk-backend backend
  - npm run build
  - npm install --prefix backend
before_script:
  - npm start --prefix backend &
  - npm start
script:
  - npm test
